package com.company.employeestate.model;

public enum EmployeeState {
	ADDED,
	IN_CHECK,
	APPROVED,
	ACTIVE,
	ALL_CHECKS_FINISHED,
	SECURITY_CHECK_STARTED,
	SECURITY_CHECK_FINISHED,
	WORK_PERMIT_CHECK_STARTED,
	WORK_PERMIT_CHECK_PENDING_VERIFICATION,
	WORK_PERMIT_CHECK_FINISHED
}
